/* =====================================================
   STORY DATABASE — Shadowing English Pro
   Arquivo carregado automaticamente por index.html
   e também utilizado pelo stories-manager.html
   Estrutura obrigatória: { level, title, sentences[{en,pt}], expressions{...} }
   ===================================================== */
window.shadowingStories = [
    {
        level: "A1",
        title: "My First Day at Work",
        sentences: [
            { en: "I was very nervous for my first day at work.", pt: "Eu estava muito nervoso para o meu primeiro dia de trabalho." },
            { en: "I [[phrasal:woke up]] at six o'clock in the morning.", pt: "Eu acordei às seis horas da manhã." },
            { en: "I [[phrasal:got up]] and went to the bathroom to take a shower.", pt: "Eu levantei e fui ao banheiro tomar banho." },
            { en: "Then I [[phrasal:put on]] my new shirt and black pants.", pt: "Depois eu vesti minha camisa nova e calça preta." },
            { en: "I went to the kitchen to make coffee and eat breakfast.", pt: "Eu fui para a cozinha fazer café e tomar café da manhã." },
            { en: "My roommate said, \"Good luck today!\"", pt: "Meu colega de quarto disse: \"Boa sorte hoje!\"" },
            { en: "\"Thanks, I'm a little scared,\" I said.", pt: "\"Obrigado, estou um pouco assustado\", eu disse." },
            { en: "\"It's [[idiom:no big deal]],\" he said. \"You'll do great.\"", pt: "\"Não é nada demais\", ele disse. \"Você vai se sair bem.\"" },
            { en: "I smiled and said, \"I hope you're right.\"", pt: "Eu sorri e disse: \"Espero que você esteja certo.\"" },
            { en: "I [[phrasal:looked for]] my bag and found it next to the door.", pt: "Eu procurei minha bolsa e a encontrei perto da porta." },
            { en: "I [[phrasal:went out]] of the apartment and walked to the subway station.", pt: "Eu saí do apartamento e andei até a estação de metrô." },
            { en: "The subway was full of people going to work.", pt: "O metrô estava cheio de gente indo para o trabalho." },
            { en: "\"[[idiom:So far, so good]],\" I thought when I sat down.", pt: "\"Até agora, tudo bem\", pensei quando me sentei." },
            { en: "After twenty minutes, I [[phrasal:got off]] at the correct station.", pt: "Depois de vinte minutos, eu desembarquei na estação correta." },
            { en: "I [[phrasal:ran into]] an old friend from school on the street.", pt: "Eu encontrei um velho amigo da escola na rua por acaso." },
            { en: "\"What are you doing here?\" he asked.", pt: "\"O que você está fazendo aqui?\", ele perguntou." },
            { en: "\"I start a new job today!\" I said.", pt: "\"Eu começo um trabalho novo hoje!\", eu disse." },
            { en: "\"That's awesome!\" he said. \"Do you want to grab lunch later?\"", pt: "\"Isso é incrível!\", ele disse. \"Você quer almoçar mais tarde?\"" },
            { en: "\"Yeah, [[idiom:sounds good]]!\" I said. \"Text me the time.\"", pt: "\"Sim, parece bom!\", eu disse. \"Me manda uma mensagem com o horário.\"" },
            { en: "When I arrived at the office, the receptionist greeted me warmly.", pt: "Quando cheguei ao escritório, a recepcionista me recebeu com carinho." },
            { en: "\"Welcome! Please, [[idiom:take a seat]]. Your manager will be right out.\"", pt: "\"Bem-vindo! Por favor, sente-se. Seu gerente já vem.\"" },
            { en: "\"[[idiom:No worries]],\" I said and sat down quietly.", pt: "\"Sem problemas\", eu disse e me sentei em silêncio." },
            { en: "Five minutes later, my manager came out to meet me.", pt: "Cinco minutos depois, meu gerente saiu para me encontrar." },
            { en: "\"Hi there! I'm Sarah. Let me show you around the office.\"", pt: "\"Olá! Sou a Sarah. Deixe eu te mostrar o escritório.\"" },
            { en: "By the end of the day, I felt much better about my new job.", pt: "No fim do dia, eu me sentia muito melhor sobre meu novo trabalho." },
            { en: "\"[[idiom:All's well that ends well]],\" I said to myself as I walked home.", pt: "\"Tudo bem que termina bem\", eu disse para mim mesmo enquanto voltava para casa." }
        ],
        expressions: {
            "woke up": { type: "Phrasal Verb", meaning: "acordei" },
            "got up": { type: "Phrasal Verb", meaning: "levantei da cama" },
            "put on": { type: "Phrasal Verb", meaning: "vesti (roupa)" },
            "looked for": { type: "Phrasal Verb", meaning: "procurei por" },
            "went out": { type: "Phrasal Verb", meaning: "saí" },
            "got off": { type: "Phrasal Verb", meaning: "desembarquei do veículo" },
            "ran into": { type: "Phrasal Verb", meaning: "encontrei por acaso" },
            "no big deal": { type: "Idiom", meaning: "não é nada demais / não tem problema" },
            "So far, so good": { type: "Idiom", meaning: "até agora, tudo bem" },
            "sounds good": { type: "Idiom", meaning: "parece bom / combinado" },
            "take a seat": { type: "Idiom", meaning: "sente-se / tome assento" },
            "No worries": { type: "Idiom", meaning: "sem problemas / relaxa" },
            "All's well that ends well": { type: "Idiom", meaning: "tudo está bem quando termina bem" }
        }
    },
    {
        level: "A2",
        title: "Weekend Trip to the Beach",
        sentences: [
            { en: "My friends and I decided to take a weekend trip to the beach last month.", pt: "Meus amigos e eu decidimos fazer uma viagem de fim de semana para a praia mês passado." },
            { en: "We [[phrasal:talked over]] our plans for a whole week before leaving.", pt: "Nós conversamos sobre nossos planos por uma semana inteira antes de sair." },
            { en: "On Friday afternoon, we packed our bags and got everything ready.", pt: "Na sexta à tarde, nós arrumamos as malas e deixamos tudo pronto." },
            { en: "My friend Jake said he would [[phrasal:pick us up]] at six o'clock.", pt: "Meu amigo Jake disse que ele nos pegaria às seis horas." },
            { en: "I was ready on time, but Jake was thirty minutes late.", pt: "Eu estava pronto na hora, mas o Jake chegou trinta minutos atrasado." },
            { en: "\"Sorry guys, my car broke down and I had to call a mechanic,\" he said.", pt: "\"Desculpa pessoal, meu carro quebrou e eu tive que chamar um mecânico\", ele disse." },
            { en: "\"[[idiom:No sweat]],\" I said. \"We have plenty of time.\"", pt: "\"Sem stress\", eu disse. \"Nós temos tempo de sobra.\"" },
            { en: "We finally hit the road around six forty-five.", pt: "Nós finalmente pegamos a estrada por volta das seis e quarenta e cinco." },
            { en: "The drive was beautiful, and we sang along to all our favorite songs.", pt: "A viagem foi linda, e nós cantamos junto todas as nossas músicas favoritas." },
            { en: "About halfway there, we [[phrasal:stopped by]] a small restaurant for dinner.", pt: "Mais ou menos na metade do caminho, nós paramos em um restaurante pequeno para jantar." },
            { en: "The food was delicious, and the portions were huge.", pt: "A comida estava deliciosa, e as porções eram enormes." },
            { en: "\"Let's share a dessert,\" said my friend Lisa. \"[[idiom:What do you say]]?\"", pt: "\"Vamos dividir uma sobremesa\", disse minha amiga Lisa. \"O que vocês acham?\"" },
            { en: "\"[[idiom:You read my mind]],\" I answered. \"I was just thinking the same thing.\"", pt: "\"Você leu minha mente\", respondi. \"Eu estava pensando a mesma coisa.\"" },
            { en: "After dinner, we [[phrasal:got back]] in the car and continued driving.", pt: "Depois do jantar, nós voltamos para o carro e continuamos a viagem." },
            { en: "We arrived at the beach house at around ten thirty at night.", pt: "Nós chegamos à casa de praia por volta das dez e trinta da noite." },
            { en: "The house was cozy, and the beach was only five minutes away on foot.", pt: "A casa era aconchegante, e a praia ficava a apenas cinco minutos a pé." },
            { en: "We were all tired, so we [[phrasal:hit the sack]] as soon as we could.", pt: "Nós estávamos todos cansados, então fomos dormir assim que pudemos." },
            { en: "The next morning, we [[phrasal:woke up]] early to watch the sunrise.", pt: "No dia seguinte, acordamos cedo para ver o nascer do sol." },
            { en: "The sky was orange and pink — it was absolutely breathtaking.", pt: "O céu estava laranja e rosa — foi absolutamente lindo de tirar o fôlego." },
            { en: "\"This was [[idiom:worth every penny]],\" Lisa said quietly.", pt: "\"Isso valeu cada centavo\", a Lisa disse baixinho." },
            { en: "We spent the whole day [[phrasal:hanging out]] on the sand, swimming, and playing volleyball.", pt: "Nós passamos o dia todo curtindo na areia, nadando e jogando vôlei." },
            { en: "By the end of the day, we were all sunburned and tired but happy.", pt: "No fim do dia, estávamos todos queimados de sol e cansados, mas felizes." },
            { en: "\"Best weekend ever!\" Jake said. \"We should do this more often.\"", pt: "\"Melhor fim de semana de todos!\", disse o Jake. \"A gente deveria fazer isso mais vezes.\"" },
            { en: "\"[[idiom:You can say that again]],\" I replied, smiling from ear to ear.", pt: "\"Pode crer\", respondi, sorrindo de orelha a orelha." }
        ],
        expressions: {
            "talked over": { type: "Phrasal Verb", meaning: "conversamos sobre / discutimos" },
            "pick us up": { type: "Phrasal Verb", meaning: "nos pegar (de carro)" },
            "stopped by": { type: "Phrasal Verb", meaning: "paramos em (passamos rapidamente)" },
            "got back": { type: "Phrasal Verb", meaning: "voltamos (para dentro)" },
            "hit the sack": { type: "Phrasal Verb", meaning: "fomos dormir / caímos na cama" },
            "woke up": { type: "Phrasal Verb", meaning: "acordamos" },
            "hanging out": { type: "Phrasal Verb", meaning: "passando o tempo / curtindo" },
            "No sweat": { type: "Idiom", meaning: "sem stress / tranquilo" },
            "hit the road": { type: "Idiom", meaning: "pegamos a estrada / saímos de viagem" },
            "What do you say": { type: "Idiom", meaning: "o que você acha / topa?" },
            "You read my mind": { type: "Idiom", meaning: "você leu minha mente / pensei a mesma coisa" },
            "worth every penny": { type: "Idiom", meaning: "valeu cada centavo" },
            "You can say that again": { type: "Idiom", meaning: "pode crer / concordo totalmente" }
        }
    },
    {
        level: "B1",
        title: "Missing an Important Deadline",
        sentences: [
            { en: "Three weeks ago, I took on a huge project at work that had a very tight deadline.", pt: "Há três semanas, eu assumi um projeto enorme no trabalho que tinha um prazo muito apertado." },
            { en: "At first, I thought I could handle it without asking for help, so I didn't say anything.", pt: "No começo, achei que conseguiria dar conta sem pedir ajuda, então não disse nada." },
            { en: "I [[phrasal:stayed up]] late every night that week trying to [[phrasal:keep up]] with all the tasks.", pt: "Eu fiquei acordado até tarde todas as noites daquela semana tentando acompanhar todas as tarefas." },
            { en: "By Wednesday, I could tell I was already falling behind schedule.", pt: "Na quarta-feira, eu já conseguia perceber que estava atrasando o cronograma." },
            { en: "My manager stopped by my desk and asked, \"How's everything going with the project?\"", pt: "Meu gerente passou na minha mesa e perguntou: \"Como está indo tudo com o projeto?\"" },
            { en: "I didn't want to admit I was struggling, so I just said, \"Fine, thanks.\"", pt: "Eu não queria admitir que estava com dificuldades, então só disse: \"Bem, obrigado.\"" },
            { en: "\"Great to hear,\" she said. \"Just remember, if you need anything, I'm here.\"", pt: "\"Que bom ouvir isso\", ela disse. \"Só lembre-se, se precisar de algo, estou aqui.\"" },
            { en: "I nodded and smiled, but deep down I knew I was [[idiom:in over my head]].", pt: "Eu acenei e sorri, mas no fundo eu sabia que estava metido em um problema maior do que eu aguentava." },
            { en: "That weekend, I had to cancel my plans with my girlfriend to work from home.", pt: "Naquele fim de semana, tive que cancelar meus planos com minha namorada para trabalhar de casa." },
            { en: "\"[[idiom:Come on]], it's our anniversary weekend,\" she said, sounding disappointed.", pt: "\"Qual é, é o fim de semana do nosso aniversário de namoro\", ela disse, parecendo desapontada." },
            { en: "\"I know, and I'm really sorry,\" I said. \"But this deadline is [[idiom:make or break]] for me.\"", pt: "\"Eu sei, e eu sinto muito\", eu disse. \"Mas esse prazo é decisivo para mim.\"" },
            { en: "She sighed and said, \"I get it, but don't let this become a habit, okay?\"", pt: "Ela suspirou e disse: \"Entendo, mas não deixe isso virar hábito, tá?\"" },
            { en: "By Monday morning, I realized I still had at least three more days of work left.", pt: "Na segunda de manhã, eu percebi que ainda tinha pelo menos mais três dias de trabalho pela frente." },
            { en: "That's when I finally decided I had to [[phrasal:come clean]] with my manager.", pt: "Foi aí que eu finalmente decidi que tinha que ser sincero com minha gerente." },
            { en: "I knocked on her office door and explained the whole situation.", pt: "Eu bati na porta do escritório dela e expliquei toda a situação." },
            { en: "To my surprise, she didn't get angry at all.", pt: "Para minha surpresa, ela não ficou brava de forma alguma." },
            { en: "\"Thanks for being honest,\" she said. \"I appreciate you not [[phrasal:putting off]] this conversation any longer.\"", pt: "\"Obrigado por ser honesto\", ela disse. \"Agradeço por não ter adiado mais essa conversa.\"" },
            { en: "She immediately assigned two more people to help me with the project.", pt: "Ela imediatamente designou mais duas pessoas para me ajudar no projeto." },
            { en: "\"Let's [[phrasal:work out]] a new plan together,\" she said. \"We can push the deadline back by three days.\"", pt: "\"Vamos montar um plano novo juntos\", ela disse. \"Podemos prorrogar o prazo em três dias.\"" },
            { en: "Working with the extra help, we managed to finish everything before the new deadline.", pt: "Trabalhando com a ajuda extra, conseguimos terminar tudo antes do novo prazo." },
            { en: "On the final day, my manager pulled me aside and said, \"Great job under pressure.\"", pt: "No último dia, minha gerente me chamou de lado e disse: \"Bom trabalho sob pressão.\"" },
            { en: "\"Thanks for not giving up on me,\" I said.", pt: "\"Obrigado por não ter desistido de mim\", eu disse." },
            { en: "\"Anytime,\" she replied. \"Just remember, [[idiom:a problem shared is a problem halved]].\"", pt: "\"Sempre\", ela respondeu. \"Só lembre-se: problema compartilhado é problema dividido.\"" },
            { en: "That experience taught me an important lesson about not being afraid to ask for help.", pt: "Essa experiência me ensinou uma lição importante sobre não ter medo de pedir ajuda." }
        ],
        expressions: {
            "stayed up": { type: "Phrasal Verb", meaning: "fiquei acordado até tarde" },
            "keep up": { type: "Phrasal Verb", meaning: "acompanhar (o ritmo)" },
            "come clean": { type: "Phrasal Verb", meaning: "ser sincero / confessar tudo" },
            "putting off": { type: "Phrasal Verb", meaning: "adiando / procrastinando" },
            "work out": { type: "Phrasal Verb", meaning: "planejar / resolver" },
            "in over my head": { type: "Idiom", meaning: "metido em algo maior do que consigo lidar" },
            "Come on": { type: "Idiom", meaning: "Qual é / Sério (expressão de frustração ou súplica)" },
            "make or break": { type: "Idiom", meaning: "decisivo / que define o sucesso ou fracasso" },
            "a problem shared is a problem halved": { type: "Idiom", meaning: "problema compartilhado é problema dividido" }
        }
    },
    {
        level: "B2",
        title: "Turning a Failed Pitch Around",
        sentences: [
            { en: "A couple of months ago, my team and I spent weeks [[phrasal:drawing up]] what we thought was an airtight marketing proposal for a major retail client.", pt: "Há alguns meses, minha equipe e eu passamos semanas elaborando o que achávamos ser uma proposta de marketing impecável para um grande cliente do varejo." },
            { en: "We pulled data, designed mockups, and rehearsed our pitch until we knew it by heart.", pt: "Nós coletamos dados, criamos protótipos visuais e ensaiamos nossa apresentação até sabê-la de cor." },
            { en: "The day of the meeting, we walked into the client's boardroom feeling confident and well-prepared.", pt: "No dia da reunião, entramos na sala de reuniões do cliente nos sentindo confiantes e bem preparados." },
            { en: "But about five minutes into the presentation, I could tell something was off.", pt: "Mas uns cinco minutos após o início da apresentação, eu consegui perceber que algo estava errado." },
            { en: "The marketing director was frowning and [[phrasal:crossing out]] things on her copy of the proposal.", pt: "A diretora de marketing estava franzindo a testa e riscando coisas na cópia dela da proposta." },
            { en: "When we finished speaking, there was a long, awkward silence.", pt: "Quando terminamos de falar, houve um silêncio longo e constrangedor." },
            { en: "\"Look,\" she said, leaning back in her chair. \"This doesn't align with what we're looking for.\"", pt: "\"Olhem\", ela disse, encostando-se na cadeira. \"Isso não está alinhado com o que procuramos.\"" },
            { en: "I felt my stomach drop, but I tried to stay calm.", pt: "Eu senti um frio na barriga, mas tentei manter a calma." },
            { en: "\"I appreciate your honesty,\" I said. \"Could you [[phrasal:point out]] exactly what's missing for you?\"", pt: "\"Agradeço sua honestidade\", eu disse. \"Você poderia apontar exatamente o que está faltando para a senhora?\"" },
            { en: "She explained that our strategy was too conventional and didn't reflect the bold direction their brand was trying to take.", pt: "Ela explicou que nossa estratégia era muito convencional e não refletia a direção ousada que a marca deles estava tentando seguir." },
            { en: "\"Frankly, it all feels a bit [[idiom:by the book]],\" she added. \"We were hoping for something that would really [[idiom:push the envelope]].\"", pt: "\"Falando francamente, tudo parece um pouco padrão\", ela acrescentou. \"Nós esperávamos algo que realmente ultrapassasse os limites.\"" },
            { en: "Instead of arguing or making excuses, I said, \"Fair enough. We completely missed the mark on this one.\"", pt: "Em vez de argumentar ou dar desculpas, eu disse: \"Tem razão. Nós erramos feio nessa.\"" },
            { en: "She raised her eyebrows, clearly surprised by my response.", pt: "Ela ergueu as sobrancelhas, claramente surpresa com minha resposta." },
            { en: "\"Here's what I'd like to propose,\" I continued. \"Give us three days to completely [[phrasal:go back to the drawing board]]. If you don't love the revised version, we'll walk away [[idiom:no strings attached]].\"", pt: "\"Eis o que eu gostaria de propor\", continuei. \"Nos dê três dias para recomeçar do zero. Se a senhora não amar a versão revisada, nós saímos sem nenhuma obrigação.\"" },
            { en: "My team members were looking at me like I had lost my mind, but the director nodded slowly.", pt: "Os membros da minha equipe estavam olhando para mim como se eu tivesse enlouquecido, mas a diretora acenou lentamente." },
            { en: "\"You've got guts,\" she said. \"[[idiom:That takes balls]]. I'll give you your three days.\"", pt: "\"Você tem coragem\", ela disse. \"Isso não é para qualquer um. Dou seus três dias.\"" },
            { en: "We left the building feeling completely defeated, but we knew we had a shot.", pt: "Saímos do prédio nos sentindo totalmente derrotados, mas sabíamos que tínhamos uma chance." },
            { en: "That night, we [[phrasal:stayed up]] until two in the morning brainstorming completely new ideas.", pt: "Naquela noite, ficamos acordados até duas da manhã trocando ideias completamente novas." },
            { en: "We threw out the original proposal entirely and started from scratch with a much more creative approach.", pt: "Nós jogamos fora a proposta original inteira e começamos do zero com uma abordagem muito mais criativa." },
            { en: "Three days later, we presented the revised pitch — and [[idiom:knocked it out of the park]].", pt: "Três dias depois, apresentamos a versão revisada — e fomos absolutamente brilhantes." },
            { en: "The director loved it, and we [[phrasal:closed on]] the contract that same afternoon.", pt: "A diretora adorou, e nós fechamos o contrato naquela mesma tarde." },
            { en: "Walking back to the office, my teammate said, \"I can't believe that actually worked. When you asked for the three days, I thought we were [[idiom:dead in the water]].\"", pt: "Voltando para o escritório, meu colega disse: \"Não consigo acreditar que realmente deu certo. Quando você pediu os três dias, achei que estávamos perdidos.\"" },
            { en: "I smiled and said, \"Sometimes the only way forward is to admit you've got it wrong — then refuse to [[phrasal:give up]].\"", pt: "Eu sorri e disse: \"Às vezes a única forma de seguir em frente é admitir que errou — e depois se recusar a desistir.\"" },
            { en: "That pitch went on to win three industry awards by the end of the year.", pt: "Aquela apresentação acabou ganhando três prêmios da indústria no fim do ano." }
        ],
        expressions: {
            "drawing up": { type: "Phrasal Verb", meaning: "elaborando / preparando" },
            "crossing out": { type: "Phrasal Verb", meaning: "riscando / eliminando (no papel)" },
            "point out": { type: "Phrasal Verb", meaning: "apontar / indicar" },
            "go back to the drawing board": { type: "Phrasal Verb", meaning: "recomeçar do zero / reformular completamente" },
            "stayed up": { type: "Phrasal Verb", meaning: "ficamos acordados" },
            "closed on": { type: "Phrasal Verb", meaning: "fechamos (acordo / contrato)" },
            "give up": { type: "Phrasal Verb", meaning: "desistir" },
            "by the book": { type: "Idiom", meaning: "padrão / seguindo as regras sem criatividade" },
            "push the envelope": { type: "Idiom", meaning: "ir além dos limites / inovar" },
            "no strings attached": { type: "Idiom", meaning: "sem condições / sem obrigações" },
            "That takes balls": { type: "Idiom", meaning: "isso exige coragem / não é para qualquer um" },
            "knocked it out of the park": { type: "Idiom", meaning: "fomos excelentes / acertamos em cheio" },
            "dead in the water": { type: "Idiom", meaning: "perdidos / sem chance de sucesso" }
        }
    },
    {
        level: "C1",
        title: "Navigating a Cross-Cultural Negotiation",
        sentences: [
            { en: "Last quarter, I was [[phrasal:tasked with]] leading a high-stakes negotiation between our American firm and a rapidly growing manufacturing company based in Seoul.", pt: "No trimestre passado, eu fui incumbido de liderar uma negociação de alto risco entre nossa empresa americana e uma empresa de manufatura de rápido crescimento sediada em Seul." },
            { en: "Having never negotiated with Korean partners before, I spent the two weeks leading up to the meeting brushing up on business etiquette and cultural norms.", pt: "Como nunca tinha negociado com parceiros coreanos antes, passei as duas semanas que antecederam a reunião estudando etiqueta de negócios e normas culturais." },
            { en: "I knew that rushing into discussions and pushing too hard for immediate answers could [[phrasal:backfire]] dramatically.", pt: "Eu sabia que apressar as discussões e pressionar demais por respostas imediatas poderia sair pela culatra de forma dramática." },
            { en: "When my team and I arrived at the client's headquarters, we were greeted warmly by Mr. Park, the CEO, and his senior team.", pt: "Quando minha equipe e eu chegamos à sede do cliente, fomos recebidos calorosamente pelo Sr. Park, o CEO, e sua equipe sênior." },
            { en: "Instead of diving straight into business, they insisted we sit down for tea and casual conversation first.", pt: "Em vez de partir direto para os negócios, eles insistiram que sentássemos para tomar chá e conversar informalmente primeiro." },
            { en: "I wanted to get to the agenda, but I knew better than to rush it — so I sat back and went with the flow.", pt: "Eu queria chegar à pauta, mas sabia que não devia apressar — então me acomodei e segui o ritmo." },
            { en: "After about forty minutes of discussing everything from our flight to the weather to Seoul's restaurant scene, Mr. Park finally [[phrasal:brought up]] the reason for our visit.", pt: "Depois de uns quarenta minutos conversando sobre tudo, desde nosso voo até o clima e a cena gastronômica de Seul, o Sr. Park finalmente mencionou o motivo de nossa visita." },
            { en: "\"So,\" he said, smiling gently. \"Tell me about your proposal. I've read through it, but I'd like to hear your thoughts directly.\"", pt: "\"Então\", ele disse, sorrindo suavemente. \"Me conte sobre sua proposta. Eu li, mas gostaria de ouvir seus pensamentos diretamente.\"" },
            { en: "I walked him through our pricing structure, distribution plan, and timeline for launch.", pt: "Eu expliquei a ele nossa estrutura de preços, plano de distribuição e cronograma de lançamento." },
            { en: "When I finished, there was a long pause — the kind where, back home, someone would usually jump in to fill the silence.", pt: "Quando terminei, houve uma pausa longa — do tipo que, lá em casa, alguém normalmente entraria para preencher o silêncio." },
            { en: "I [[phrasal:held back]] the urge to keep talking and just waited calmly.", pt: "Eu contive o impulso de continuar falando e apenas esperei calmamente." },
            { en: "Mr. Park nodded slowly. \"The numbers are reasonable, and your distribution plan is well thought out,\" he said carefully.", pt: "O Sr. Park acenou lentamente. \"Os números são razoáveis, e seu plano de distribuição é bem pensado\", ele disse com cuidado." },
            { en: "\"But...\" I prompted gently.", pt: "\"Mas...\" eu suavizei, incentivando-o a continuar." },
            { en: "\"But we have some concerns about the exclusivity clause,\" he replied. \"You're asking for three years of exclusive rights. In our experience, that's [[idiom:asking a lot]] for a first-time partnership.\"", pt: "\"Mas temos algumas preocupações com a cláusula de exclusividade\", ele respondeu. \"Vocês estão pedindo três anos de direitos exclusivos. Em nossa experiência, isso é pedir muito para uma parceria de primeira viagem.\"" },
            { en: "I took a moment to consider my response. I didn't want to [[phrasal:give in]] completely on exclusivity, but I also didn't want to [[phrasal:rub him the wrong way]].", pt: "Eu demorei um momento para considerar minha resposta. Não queria ceder completamente na exclusividade, mas também não queria criar antipatia." },
            { en: "\"I completely understand where you're coming from,\" I began. \"Three years does feel like a big commitment when you haven't seen results yet.\"", pt: "\"Entendo perfeitamente seu ponto de vista\", comecei. \"Três anos realmente parecem um compromisso grande quando você ainda não viu resultados.\"" },
            { en: "That seemed to land well. Mr. Park leaned forward slightly — a good sign.", pt: "Isso pareceu funcionar bem. O Sr. Park se inclinou para frente ligeiramente — um bom sinal." },
            { en: "\"Here's a middle ground,\" I continued. \"[[idiom:Hear me out]]. What if we start with an eighteen-month exclusive period, with an automatic renewal for another eighteen months only if we hit our mutually agreed-upon KPIs?\"", pt: "\"Eis um meio-terma\", continuei. \"Me ouça. Que tal começarmos com um período de exclusividade de dezoito meses, com renovação automática por mais dezoito meses apenas se atingirmos os KPIs mutuamente acordados?\"" },
            { en: "Mr. Park and his team exchanged a few quiet words in Korean — words I obviously couldn't understand, but whose tone I could read.", pt: "O Sr. Park e sua equipe trocaram algumas palavras baixas em coreano — palavras que obviamente eu não podia entender, mas cujo tom eu conseguia ler." },
            { en: "\"That's an interesting proposal,\" he said after a moment. \"Let me think on it and consult with our legal team. Can we come back to this tomorrow morning?\"", pt: "\"É uma proposta interessante\", ele disse depois de um momento. \"Deixe eu pensar e consultar nosso time jurídico. Podemos voltar a isso amanhã de manhã?\"" },
            { en: "\"Absolutely,\" I said. \"[[idiom:Take all the time you need]]. We're not going anywhere.\"", pt: "\"Com certeza\", eu disse. \"Leve todo o tempo que precisar. Não estamos indo a lugar nenhum.\"" },
            { en: "That night, over dinner with my team, I told them not to get their hopes up — but also not to lose faith.", pt: "Naquela noite, durante o jantar com minha equipe, eu disse a eles para não criarem muitas expectativas — mas também para não perderem a fé." },
            { en: "The next morning, we walked into the same room to find Mr. Park already sitting at the table with a printed document in front of him.", pt: "Na manhã seguinte, entramos na mesma sala e encontramos o Sr. Park já sentado à mesa com um documento impresso à sua frente." },
            { en: "\"I've had my team [[phrasal:draw up]] a revised contract incorporating your eighteen-month proposal,\" he said, sliding it across the table. \"We'd like to move forward, provided both legal teams can sign off by the end of the week.\"", pt: "\"Pedi que minha equipe elaborasse um contrato revisado incorporando sua proposta de dezoito meses\", ele disse, deslizando-o pela mesa. \"Gostaríamos de seguir adiante, desde que ambos os times jurídicos aprovem até o fim da semana.\"" },
            { en: "I could barely contain my excitement, but I kept my composure and just smiled.", pt: "Eu quase não conseguia conter minha empolgação, mas mantive a compostura e apenas sorri." },
            { en: "\"That's wonderful news,\" I said. \"We couldn't be happier to be entering this partnership with you.\"", pt: "\"Isso é uma notícia maravilhosa\", eu disse. \"Não poderíamos estar mais felizes em iniciar essa parceria com vocês.\"" },
            { en: "On the flight home, I reflected on how different the entire process had been from a typical American negotiation — and how patience, respect, and a willingness to find middle ground had [[idiom:paid off]] in ways I could never have anticipated.", pt: "No voo de volta, refliti sobre como todo o processo tinha sido diferente de uma negociação americana típica — e como a paciência, o respeito e a disposição para encontrar um meio-terma valeram a pena de maneiras que eu nunca poderia ter antecipado." }
        ],
        expressions: {
            "tasked with": { type: "Phrasal Verb", meaning: "incumbido de / designado para" },
            "backfire": { type: "Phrasal Verb", meaning: "sair pela culatra / dar errado contra quem fez" },
            "brought up": { type: "Phrasal Verb", meaning: "mencionou / trouxe à tona" },
            "held back": { type: "Phrasal Verb", meaning: "contive (o impulso)" },
            "give in": { type: "Phrasal Verb", meaning: "ceder / render-se" },
            "rub him the wrong way": { type: "Phrasal Verb", meaning: "causar antipatia / irritar" },
            "draw up": { type: "Phrasal Verb", meaning: "elaborar / preparar (documento)" },
            "asking a lot": { type: "Idiom", meaning: "pedindo muito / exigindo algo elevado" },
            "Hear me out": { type: "Idiom", meaning: "Me ouça até o fim / Me dê uma chance de explicar" },
            "Take all the time you need": { type: "Idiom", meaning: "Leve todo o tempo que precisar / sem pressa" },
            "paid off": { type: "Idiom", meaning: "valeu a pena / deu resultado positivo" }
        }
    },
    {
        level: "C2",
        title: "The Dilemma of Taking a Counteroffer",
        sentences: [
            { en: "For the better part of eight years, I had poured my heart and soul into the same marketing agency, working my way up from a junior copywriter to head of the creative department.", pt: "Durante a maior parte de oito anos, eu depositei meu coração e alma na mesma agência de marketing, subindo na carreira de redator júnior até chefe do departamento de criação." },
            { en: "I loved the team, genuinely enjoyed most of the work, and had built relationships with colleagues that extended far beyond the walls of the office.", pt: "Eu amava a equipe, gostava genuinamente da maior parte do trabalho e tinha construído relacionamentos com colegas que iam muito além das paredes do escritório." },
            { en: "But around the six-month mark of last year, I started to feel like I was [[phrasal:treading water]] — going through the motions, delivering good work, but not growing or pushing myself in the way I had been early on.", pt: "Mas por volta do sexto mês do ano passado, eu comecei a sentir que estava andando na esteira — fazendo as coisas por fazer, entregando um bom trabalho, mas não crescendo ou me desafiando da forma como fazia no começo." },
            { en: "That quiet sense of stagnation was, I'll admit, part of the reason I agreed to have coffee with a recruiter who had been [[phrasal:reaching out]] to me for months.", pt: "Essa sensação silenciosa de estagnação foi, admito, parte da razão pela qual concordei em tomar café com um recrutador que vinha me contatando há meses." },
            { en: "At first, it was just a conversation — no strings attached, nothing serious.", pt: "No começo, foi só uma conversa — sem compromisso, nada sério." },
            { en: "But by the end of that first meeting, he was painting a picture of a role that sounded almost custom-designed for me: creative director at a boutique brand consultancy, smaller team, higher salary, and the kind of strategic, brand-defining work I had been craving.", pt: "Mas ao final daquela primeira reunião, ele estava descrevendo um cargo que parecia quase feito sob medida para mim: diretor de criação em uma consultoria de marca boutique, equipe menor, salário mais alto, e o tipo de trabalho estratégico que define marcas, algo que eu estava desejando há tempos." },
            { en: "Two interviews later, they [[phrasal:came through]] with a formal offer that exceeded even my expectations — a thirty percent pay bump, a signing bonus, and a clear path to partner within three years.", pt: "Duas entrevistas depois, eles chegaram com uma oferta formal que superou até minhas expectativas — um aumento de trinta por cento, bônus de contratação e um caminho claro para sócio em até três anos." },
            { en: "I should have been elated. And part of me was — but a larger part felt [[idiom:torn between two worlds]].", pt: "Eu deveria ter estado radiante. E parte de mim estava — mas uma parte maior se sentia dividida entre dois mundos." },
            { en: "I spent the weekend going [[phrasal:back and forth]] in my head, drafting resignation letters in my mind and then tearing them up just as quickly.", pt: "Passei o fim de semana alternando decisões na minha cabeça, rascunhando cartas de demissão na minha mente e rasgando-as logo em seguida." },
            { en: "On Monday morning, I resolved to hand in my notice. I was sitting in my car outside the office, working up the courage to go in, when my phone rang — it was my boss, Rebecca, asking if I could stop by her office first thing.", pt: "Na segunda de manhã, eu me decidi a entregar a carta de demissão. Estava sentado no carro fora do escritório, reunindo coragem para entrar, quando meu telefone tocou — era a minha chefe, Rebecca, pedindo se eu poderia passar no escritório dela antes de começar qualquer coisa." },
            { en: "I walked in, already anticipating the conversation ahead of me, and she cut straight to the chase.", pt: "Eu entrei, já antecipando a conversa que estava por vir, e ela foi direta ao assunto." },
            { en: "\"I know you've been interviewing,\" she said. \"And I don't blame you. But before you make a final decision, I want to put something on the table.\"", pt: "\"Sei que você tem feito entrevistas\", ela disse. \"E eu não te culpo. Mas antes que você tome uma decisão final, quero colocar algo sobre a mesa.\"" },
            { en: "I was, to say the least, [[idiom:taken aback]]. I had thought I was being discreet, but clearly, word traveled.", pt: "Eu estava, para dizer o mínimo, surpreso. Eu achava que estava sendo discreto, mas claramente a notícia se espalhou." },
            { en: "She proceeded to lay out a counteroffer that was, quite honestly, impressive: a twenty-two percent raise immediately, a promotion to executive creative director, a dedicated team of four senior creatives reporting directly to me, and the freedom to pick and choose which clients we took on.", pt: "Ela então apresentou uma contraproposta que, honestamente, era impressionante: aumento de vinte e dois por cento imediato, promoção a diretor de criação executivo, uma equipe dedicada de quatro criativos sêniores reportando diretamente a mim, e a liberdade de escolher quais clientes atenderíamos." },
            { en: "\"We don't want to lose you,\" she said quietly. \"But I'm also not going to [[phrasal:beg you to stay]]. If your heart is already somewhere else, I'll understand. But I wanted you to know what you'd be walking away from.\"", pt: "\"Não queremos te perder\", ela disse baixinho. \"Mas também não vou implorar para que fique. Se seu coração já está em outro lugar, eu vou entender. Mas queria que soubesse do que você estaria se afastando.\"" },
            { en: "Now I really had a dilemma on my hands — not a fabricated, middle-of-the-night, overthinking kind of dilemma, but a genuine, [[idiom:no-two-ways-about-it]] crossroads with no obvious right answer.", pt: "Agora eu realmente tinha um dilema nas mãos — não um dilema fabricado, do tipo que a gente pensa de madrugada pensando demais, mas uma encruzilhada genuína, sem meio termo, sem resposta óbvia." },
            { en: "The new company offered something intangible — a fresh start, the thrill of reinvention, the chance to prove myself again in a completely different environment.", pt: "A empresa nova oferecia algo intangível — um recomeço, a emoção de se reinventar, a chance de me provar novamente em um ambiente completamente diferente." },
            { en: "The counteroffer, on the other hand, came wrapped in the warmth of the familiar: people I loved, institutional knowledge I had spent eight years building, and the chance to [[phrasal:steer]] the department I had helped create toward a new vision of my own design.", pt: "A contraproposta, por outro lado, vinha envolta no calor do familiar: pessoas que eu amava, conhecimento institucional que eu tinha passado oito anos construindo, e a chance de guiar o departamento que eu tinha ajudado a criar para uma nova visão do meu próprio desenho." },
            { en: "I asked for forty-eight hours to make up my mind, and Rebecca [[phrasal:agreed to]] it without hesitation.", pt: "Pedi quarenta e oito horas para tomar uma decisão, e Rebecca concordou sem hesitar." },
            { en: "Those forty-eight hours were, without exaggeration, some of the most mentally and emotionally exhausting of my adult life.", pt: "Aqueles quarenta e oito horas foram, sem exagero, algumas das mais mentalmente e emocionalmente desgastantes da minha vida adulta." },
            { en: "I [[phrasal:talked it through]] with my partner, with my parents, with two friends I trusted implicitly — and they all offered different perspectives, which helped precisely not at all.", pt: "Conversei exaustivamente sobre isso com minha parceira, com meus pais, com dois amigos em quem confiava cegamente — e todos ofereceram perspectivas diferentes, o que não ajudou em absolutamente nada." },
            { en: "Ultimately, I made my decision not by drawing up a pros and cons list — though I did, and it was almost perfectly even — but by sitting in silence and asking myself one question: \"At the end of my career, when I look back, which choice will I regret not having made more?\"", pt: "Por fim, tomei minha decisão não fazendo uma lista de prós e contras — embora tenha feito, e ela estava quase perfeitamente equilibrada — mas sentando em silêncio e me perguntando uma coisa: \"No fim da minha carreira, quando eu olhar para trás, de qual escolha eu mais me arrependerei de não ter feito?\"" },
            { en: "The answer, when it came to me, was crystal clear — and surprising, because it contradicted what I had spent the previous few days trying to convince myself of.", pt: "A resposta, quando me veio à mente, foi cristalina — e surpreendente, porque contradizia o que eu tinha passado os dias anteriores tentando convencer a mim mesmo." },
            { en: "I chose the new opportunity — not because the money was better, or the title was flashier, but because part of growing as a professional and as a person is learning how to [[phrasal:let go]] of what is safe and known, and step into the unknown, even when every fiber of your being is screaming to stay where the ground feels solid.", pt: "Eu escolhi a nova oportunidade — não porque o dinheiro fosse melhor, ou o cargo mais chamativo, mas porque parte de crescer como profissional e como pessoa é aprender a deixar ir o que é seguro e conhecido, e mergulhar no desconhecido, mesmo quando cada fibra do seu ser está gritando para ficar onde o chão parece firme." },
            { en: "When I walked into Rebecca's office to deliver my answer, she didn't seem disappointed — she seemed to have already expected it.", pt: "Quando entrei no escritório da Rebecca para dar minha resposta, ela não pareceu decepcionada — parecia já ter esperado por isso." },
            { en: "\"I had a feeling,\" she said, standing up to shake my hand. \"You've always been the kind of person who needs to [[phrasal:strike out]] on his own every now and then. Don't be a stranger, okay?\"", pt: "\"Eu tinha um pressentimento\", ela disse, levantando-se para apertar minha mão. \"Você sempre foi o tipo de pessoa que precisa seguir seu próprio caminho de vez em quando. Não desapareça, tá?\"" },
            { en: "Leaving the building that afternoon for the last time, with a box of my personal things in the trunk of my car, I felt both sad and exhilarated — a strange, bittersweet cocktail of emotion that I'd later learn is simply the natural [[idiom:order of the day]] whenever you choose growth over comfort.", pt: "Saindo do prédio naquela tarde pela última vez, com uma caixa das minhas coisas pessoais no porta-malas do carro, eu me senti triste e animado ao mesmo tempo — um coquetel estranho e agridoce de emoção que eu mais tarde descobri ser simplesmente a ordem natural das coisas sempre que você escolhe o crescimento em vez do conforto." },
            { en: "Six months into the new job, it hasn't been without its challenges — but I haven't once looked back and wondered if I made the wrong call.", pt: "Seis meses no novo emprego, não tem sido sem desafios — mas eu nunca olhei para trás e me perguntei se fiz a escolha errada." },
            { en: "And at the end of the day, that's really all you can ask for: to live with your decisions in peace, trusting that whatever road you [[phrasal:take on]], the journey itself will teach you exactly what you need to learn.", pt: "E no fim das contas, é realmente tudo que se pode pedir: viver com suas decisões em paz, confiando que seja qual for o caminho que você seguir, a própria jornada vai te ensinar exatamente o que você precisa aprender." }
        ],
        expressions: {
            "treading water": { type: "Phrasal Verb", meaning: "andando na esteira / sem progredir" },
            "reaching out": { type: "Phrasal Verb", meaning: "tentando contato / se comunicando comigo" },
            "came through": { type: "Phrasal Verb", meaning: "apresentaram (a oferta)" },
            "back and forth": { type: "Phrasal Verb", meaning: "alternando indecisamente / indo e vindo" },
            "beg you to stay": { type: "Phrasal Verb", meaning: "implorar para que fique" },
            "steer": { type: "Phrasal Verb", meaning: "dirigir / guiar (rumo)" },
            "agreed to": { type: "Phrasal Verb", meaning: "concordou com" },
            "talked it through": { type: "Phrasal Verb", meaning: "conversei exaustivamente sobre o assunto" },
            "let go": { type: "Phrasal Verb", meaning: "deixar ir / soltar (com segurança)" },
            "strike out": { type: "Phrasal Verb", meaning: "seguir seu próprio caminho / sair sozinho" },
            "take on": { type: "Phrasal Verb", meaning: "seguir / encarar (o caminho)" },
            "torn between two worlds": { type: "Idiom", meaning: "dividido entre duas opções / dois mundos" },
            "taken aback": { type: "Idiom", meaning: "surpreso / desprevenido" },
            "no-two-ways-about-it": { type: "Idiom", meaning: "sem meio-terma / sem margem para dúvidas" },
            "order of the day": { type: "Idiom", meaning: "ordem natural das coisas / o que é comum esperar" }
        }
    }
];

/* Exporta também como CommonJS/ES module caso o arquivo seja usado em Node */
if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.shadowingStories;
}
